# Form implementation generated from reading ui file 'UI\image_viewr.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(687, 524)
        Form.setMinimumSize(QtCore.QSize(687, 524))
        Form.setMaximumSize(QtCore.QSize(687, 524))
        Form.setStyleSheet("#Form{\n"
"background-color:#252422;\n"
"border-radius:20px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.imageLabel = QtWidgets.QLabel(parent=Form)
        self.imageLabel.setMinimumSize(QtCore.QSize(663, 390))
        self.imageLabel.setMaximumSize(QtCore.QSize(663, 390))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.imageLabel.setFont(font)
        self.imageLabel.setStyleSheet("QLabel{\n"
"background-color:#383632;\n"
"color:white;\n"
"border-radius: 20px;\n"
"}")
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(parent=Form)
        self.saveButton.setMinimumSize(QtCore.QSize(121, 41))
        self.saveButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.signupSwitchButton = QtWidgets.QPushButton(parent=Form)
        self.signupSwitchButton.setMinimumSize(QtCore.QSize(121, 41))
        self.signupSwitchButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.signupSwitchButton.setFont(font)
        self.signupSwitchButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.signupSwitchButton.setObjectName("signupSwitchButton")
        self.horizontalLayout.addWidget(self.signupSwitchButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.signupSwitchButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.imageLabel.setText(_translate("Form", "Loading Image..."))
        self.saveButton.setText(_translate("Form", "Save"))
        self.signupSwitchButton.setText(_translate("Form", "Cancel"))
