# Form implementation generated from reading ui file 'UI\Login_SignUp_Form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(905, 725)
        Form.setMinimumSize(QtCore.QSize(905, 725))
        Form.setMaximumSize(QtCore.QSize(905, 725))
        Form.setStyleSheet("#Form{\n"
"background-color:rgb(37, 36, 34);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(9, 9, 9, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setMinimumSize(QtCore.QSize(121, 41))
        self.exitButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loginSwitchButton = QtWidgets.QPushButton(parent=Form)
        self.loginSwitchButton.setMinimumSize(QtCore.QSize(121, 41))
        self.loginSwitchButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.loginSwitchButton.setFont(font)
        self.loginSwitchButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.loginSwitchButton.setObjectName("loginSwitchButton")
        self.horizontalLayout.addWidget(self.loginSwitchButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.signupSwitchButton = QtWidgets.QPushButton(parent=Form)
        self.signupSwitchButton.setMinimumSize(QtCore.QSize(121, 41))
        self.signupSwitchButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.signupSwitchButton.setFont(font)
        self.signupSwitchButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.signupSwitchButton.setObjectName("signupSwitchButton")
        self.horizontalLayout.addWidget(self.signupSwitchButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.page)
        self.widget_3.setMinimumSize(QtCore.QSize(412, 565))
        self.widget_3.setMaximumSize(QtCore.QSize(412, 565))
        self.widget_3.setStyleSheet("background:#403D39;\n"
"border-radius: 20px;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_7 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(81, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_8.setMaximumSize(QtCore.QSize(160, 149))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/img/logo2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(81, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_10 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_7.setMaximumSize(QtCore.QSize(276, 191))
        self.label_7.setStyleSheet("font: 24pt \"Kdam Thmor Pro\" ;\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem7)
        self.frame_9 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_9.setMinimumSize(QtCore.QSize(374, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(374, 50))
        self.frame_9.setStyleSheet("  background-color:rgb(198, 191, 180); ")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_12.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/profile.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_10.addWidget(self.pushButton_12)
        self.userNameLoginInput = QtWidgets.QLineEdit(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.userNameLoginInput.setFont(font)
        self.userNameLoginInput.setStyleSheet("background-color:rgb(198, 191, 180);\n"
"font: 11pt \"Kdam Thmor Pro\";margin-top:5px")
        self.userNameLoginInput.setObjectName("userNameLoginInput")
        self.horizontalLayout_10.addWidget(self.userNameLoginInput)
        self.verticalLayout.addWidget(self.frame_9, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.frame_8 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_8.setMinimumSize(QtCore.QSize(374, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(374, 50))
        self.frame_8.setStyleSheet("  background-color:rgb(198, 191, 180); ")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_11.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/password.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.passwordLoginInput = QtWidgets.QLineEdit(parent=self.frame_8)
        self.passwordLoginInput.setStyleSheet("background-color:rgb(198, 191, 180);\n"
"font: 11pt \"Kdam Thmor Pro\";margin-top:5px")
        self.passwordLoginInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLoginInput.setObjectName("passwordLoginInput")
        self.horizontalLayout_6.addWidget(self.passwordLoginInput)
        self.showPassword = QtWidgets.QPushButton(parent=self.frame_8)
        self.showPassword.setStyleSheet("QPushButton:pressed{\n"
"icon:url(:/img/output-onlinepngtools (1).png);\n"
"}")
        self.showPassword.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/output-onlinepngtools.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassword.setIcon(icon2)
        self.showPassword.setIconSize(QtCore.QSize(25, 25))
        self.showPassword.setCheckable(True)
        self.showPassword.setObjectName("showPassword")
        self.horizontalLayout_6.addWidget(self.showPassword)
        self.verticalLayout.addWidget(self.frame_8, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem9)
        self.rememberMe = QtWidgets.QCheckBox(parent=self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro 13")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.rememberMe.setFont(font)
        self.rememberMe.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rememberMe.setStyleSheet("QCheckBox{\n"
"font: 10pt \"Kdam Thmor Pro\" bold;\n"
"margin-top:5px;\n"
"margin-left:20px;\n"
"color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: gray;\n"
"    border-radius: 10px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: white white black black;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox:checked, QCheckBox::indicator:checked {\n"
"    border-color: black black white white;\n"
"}\n"
"\n"
"")
        self.rememberMe.setObjectName("rememberMe")
        self.verticalLayout.addWidget(self.rememberMe)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.frame_11 = QtWidgets.QFrame(parent=self.widget_3)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.loginButton = QtWidgets.QPushButton(parent=self.frame_11)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 50))
        self.loginButton.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_8.addWidget(self.loginButton)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout.addWidget(self.frame_11)
        spacerItem13 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem13)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_2.setMinimumSize(QtCore.QSize(341, 527))
        self.widget_2.setMaximumSize(QtCore.QSize(412, 565))
        self.widget_2.setSizeIncrement(QtCore.QSize(412, 565))
        self.widget_2.setStyleSheet("background:#403D39;\n"
"border-radius: 20px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.frame_12 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(81, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_9.setMaximumSize(QtCore.QSize(160, 149))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/img/logo2.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem16 = QtWidgets.QSpacerItem(81, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_6.setMaximumSize(QtCore.QSize(177, 191))
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 24pt \"Kdam Thmor Pro\" ;\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.verticalLayout_4.addWidget(self.frame_13)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("  background-color:rgb(198, 191, 180); ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.userNameSignUpInput = QtWidgets.QLineEdit(parent=self.frame_3)
        self.userNameSignUpInput.setStyleSheet("background-color:rgb(198, 191, 180);\n"
"font: 11pt \"Kdam Thmor Pro\";\n"
"margin-top:5px;")
        self.userNameSignUpInput.setObjectName("userNameSignUpInput")
        self.horizontalLayout_4.addWidget(self.userNameSignUpInput)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.frame_6 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setStyleSheet("  background-color:rgb(198, 191, 180); ")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.passwordSignUpInput = QtWidgets.QLineEdit(parent=self.frame_6)
        self.passwordSignUpInput.setStyleSheet("background-color:rgb(198, 191, 180);\n"
"font: 11pt \"Kdam Thmor Pro\";\n"
"margin-top:5px;")
        self.passwordSignUpInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordSignUpInput.setObjectName("passwordSignUpInput")
        self.horizontalLayout_7.addWidget(self.passwordSignUpInput)
        self.showPassword_2 = QtWidgets.QPushButton(parent=self.frame_6)
        self.showPassword_2.setStyleSheet("QPushButton:pressed{\n"
"icon:url(:/img/output-onlinepngtools (1).png);\n"
"}")
        self.showPassword_2.setText("")
        self.showPassword_2.setIcon(icon2)
        self.showPassword_2.setIconSize(QtCore.QSize(25, 25))
        self.showPassword_2.setCheckable(True)
        self.showPassword_2.setObjectName("showPassword_2")
        self.horizontalLayout_7.addWidget(self.showPassword_2)
        self.verticalLayout_4.addWidget(self.frame_6)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem21)
        self.frame_4 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setStyleSheet("  background-color:rgb(198, 191, 180); ")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.confirmPasswordSignUpInput = QtWidgets.QLineEdit(parent=self.frame_4)
        self.confirmPasswordSignUpInput.setStyleSheet("background-color:rgb(198, 191, 180);\n"
"font: 11pt \"Kdam Thmor Pro\";\n"
"margin-top:5px;")
        self.confirmPasswordSignUpInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPasswordSignUpInput.setObjectName("confirmPasswordSignUpInput")
        self.horizontalLayout_5.addWidget(self.confirmPasswordSignUpInput)
        self.showPassword_3 = QtWidgets.QPushButton(parent=self.frame_4)
        self.showPassword_3.setStyleSheet("QPushButton:pressed{\n"
"icon:url(:/img/output-onlinepngtools (1).png);\n"
"}")
        self.showPassword_3.setText("")
        self.showPassword_3.setIcon(icon2)
        self.showPassword_3.setIconSize(QtCore.QSize(25, 25))
        self.showPassword_3.setCheckable(True)
        self.showPassword_3.setObjectName("showPassword_3")
        self.horizontalLayout_5.addWidget(self.showPassword_3)
        self.verticalLayout_4.addWidget(self.frame_4)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem22)
        self.frame_14 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem23 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem23)
        self.signUpButton = QtWidgets.QPushButton(parent=self.frame_14)
        self.signUpButton.setMinimumSize(QtCore.QSize(0, 50))
        self.signUpButton.setMaximumSize(QtCore.QSize(300, 50))
        self.signUpButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.signUpButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.signUpButton.setFont(font)
        self.signUpButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.horizontalLayout_14.addWidget(self.signUpButton)
        spacerItem24 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem24)
        self.verticalLayout_4.addWidget(self.frame_14)
        spacerItem25 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem25)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.exitButton.pressed.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exitButton.setText(_translate("Form", "Exit"))
        self.loginSwitchButton.setText(_translate("Form", "Login"))
        self.signupSwitchButton.setText(_translate("Form", "Sign up"))
        self.label_7.setText(_translate("Form", "Welcome Back"))
        self.userNameLoginInput.setPlaceholderText(_translate("Form", "User Name"))
        self.passwordLoginInput.setPlaceholderText(_translate("Form", "Password"))
        self.rememberMe.setText(_translate("Form", "Remember Me"))
        self.loginButton.setText(_translate("Form", "LOG IN"))
        self.loginButton.setShortcut(_translate("Form", "Return"))
        self.label_6.setText(_translate("Form", "Sign Up"))
        self.userNameSignUpInput.setPlaceholderText(_translate("Form", "User Name"))
        self.passwordSignUpInput.setPlaceholderText(_translate("Form", "Password"))
        self.confirmPasswordSignUpInput.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.signUpButton.setText(_translate("Form", "SIGN UP"))
        self.signUpButton.setShortcut(_translate("Form", "Return"))
