# Form implementation generated from reading ui file 'UI\message_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(695, 544)
        Form.setMaximumSize(QtCore.QSize(695, 544))
        Form.setStyleSheet("#Form{\n"
"background-color:#252422;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(33, 50, 33, 50)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(parent=Form)
        self.saveButton.setMinimumSize(QtCore.QSize(121, 41))
        self.saveButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.signupSwitchButton = QtWidgets.QPushButton(parent=Form)
        self.signupSwitchButton.setMinimumSize(QtCore.QSize(121, 41))
        self.signupSwitchButton.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        self.signupSwitchButton.setFont(font)
        self.signupSwitchButton.setStyleSheet("QPushButton{\n"
"background-color: #EB5E28;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 100, 43);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(208, 81, 35);\n"
"}")
        self.signupSwitchButton.setObjectName("signupSwitchButton")
        self.horizontalLayout.addWidget(self.signupSwitchButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.messageInput = QtWidgets.QTextEdit(parent=Form)
        self.messageInput.setEnabled(False)
        self.messageInput.setStyleSheet("QTextEdit{\n"
"background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"padding:30px 30px;\n"
"}\n"
"\n"
"")
        self.messageInput.setObjectName("messageInput")
        self.gridLayout.addWidget(self.messageInput, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro")
        font.setPointSize(27)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"background:transparent;\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.copyButton = QtWidgets.QPushButton(parent=Form)
        self.copyButton.setMinimumSize(QtCore.QSize(75, 25))
        self.copyButton.setMaximumSize(QtCore.QSize(75, 25))
        self.copyButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(56, 54, 50);\n"
"color:white;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(80, 77, 72);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(35, 34, 31);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/copy-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.copyButton.setIcon(icon)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_2.addWidget(self.copyButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.signupSwitchButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Save"))
        self.signupSwitchButton.setText(_translate("Form", "Cancel"))
        self.label_13.setText(_translate("Form", "Your Message"))
        self.copyButton.setText(_translate("Form", "Copy"))
