# Form implementation generated from reading ui file 'UI/loader.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QFontDatabase

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 282)
        self.vLayout = QtWidgets.QVBoxLayout(Form)
        self.vLayout.setObjectName("vlayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        
        font_id = QFontDatabase.addApplicationFont(":/Fonts/Fonts/KdamThmorPro-Regular.ttf")
        family = QFontDatabase.applicationFontFamilies(font_id)[0]
        
        self.label02 = QtWidgets.QLabel(parent=Form)
        self.label02.setText('Loading....')
        self.label02.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label02.setStyleSheet("color:white;\n"+
                                   f"font-family:{family};\n"+
                                   "font-size:18px;\n"+
                                   "background: transparent;")
        
        self.vLayout.addWidget(self.label)
        self.vLayout.addWidget(self.label02)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
