# Form implementation generated from reading ui file 'UI\main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 804)
        MainWindow.setStyleSheet("\n"
"\n"
"background-color: rgb(37, 36, 34);\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/dark_orange/img/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(32)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("background-color: rgb(64, 61, 57);\n"
"width: 185;\n"
"left: -25px;\n"
"border-top-right-radius: 50px;\n"
"border-bottom-right-radius: 50px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 35, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("top: 135px;\n"
"left: 43px;\n"
"font-family: Kdam Thmor Pro;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Kdam Thmor Pro")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("top: 135px;\n"
"left: 43px;\n"
"font-family: Kdam Thmor Pro;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 86, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: rgb(91, 87, 81);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{  \n"
"    border-radius:10px;\n"
"    background-color: rgba(235, 94, 40, 1);\n"
"}\n"
"")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: rgb(91, 87, 81);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{  \n"
"    border-radius:10px;\n"
"    background-color: rgba(235, 94, 40, 1);\n"
"}\n"
"")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/encoder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_3.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_3.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: rgb(91, 87, 81);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{  \n"
"    border-radius:10px;\n"
"    background-color: rgba(235, 94, 40, 1);\n"
"}\n"
"")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/decoder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_4.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_4.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: rgb(91, 87, 81);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{  \n"
"    border-radius:10px;\n"
"    background-color: rgba(235, 94, 40, 1);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/saves.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 141, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_4.addItem(spacerItem5)
        self.LogoutButton = QtWidgets.QPushButton(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.LogoutButton.setFont(font)
        self.LogoutButton.setStyleSheet("\n"
"QPushButton:hover\n"
"{\n"
"    icon:url(:/img/Quit_Colorfull.png);\n"
"}\n"
"")
        self.LogoutButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/quit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.LogoutButton.setIcon(icon5)
        self.LogoutButton.setIconSize(QtCore.QSize(40, 40))
        self.LogoutButton.setObjectName("LogoutButton")
        self.verticalLayout_4.addWidget(self.LogoutButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_4.addItem(spacerItem6)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("background-image:url(:/img/BG.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-origin: content;\n"
"background-attachment: fixed;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_14.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.frame_14.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_14.setAutoFillBackground(False)
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setSpacing(7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_12.setMinimumSize(QtCore.QSize(300, 100))
        self.label_12.setMaximumSize(QtCore.QSize(500, 500))
        self.label_12.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 50px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #EB5E28;\n"
"background:transparent;\n"
"")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_13.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 36px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"background:transparent;\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.messageInput = QtWidgets.QTextEdit(parent=self.frame_14)
        self.messageInput.setStyleSheet("QTextEdit{\n"
"background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"padding:30px 30px;\n"
"}\n"
"\n"
"")
        self.messageInput.setObjectName("messageInput")
        self.verticalLayout_7.addWidget(self.messageInput)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(100, 100))
        self.label_14.setMaximumSize(QtCore.QSize(250, 100))
        self.label_14.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 36px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"background:transparent;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_5.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(1000, 150))
        self.frame_5.setStyleSheet("background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.imagePathInput = QtWidgets.QLineEdit(parent=self.frame_5)
        self.imagePathInput.setStyleSheet("background:transparent;\n"
"padding:0px 30px;")
        self.imagePathInput.setReadOnly(True)
        self.imagePathInput.setObjectName("imagePathInput")
        self.horizontalLayout_4.addWidget(self.imagePathInput)
        self.selectImageButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.selectImageButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(56, 54, 50);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"icon:url(:/img/880eef29f787c838e5be91b50d4f475dd29b0bfc (1).ico);\n"
"}")
        self.selectImageButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.selectImageButton.setIcon(icon6)
        self.selectImageButton.setIconSize(QtCore.QSize(60, 25))
        self.selectImageButton.setObjectName("selectImageButton")
        self.horizontalLayout_4.addWidget(self.selectImageButton)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_15.setMinimumSize(QtCore.QSize(100, 100))
        self.label_15.setMaximumSize(QtCore.QSize(250, 100))
        self.label_15.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 36px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"background:transparent;\n"
"")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(1000, 150))
        self.frame_3.setStyleSheet("background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordInput = QtWidgets.QLineEdit(parent=self.frame_3)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 0))
        self.passwordInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.passwordInput.setStyleSheet("background:transparent;\n"
"padding:0px 20px;")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.horizontalLayout_2.addWidget(self.passwordInput)
        self.showPassword_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.showPassword_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(56, 54, 50);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"icon:url(:/img/output-onlinepngtools (1).png);\n"
"}")
        self.showPassword_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/output-onlinepngtools.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassword_2.setIcon(icon7)
        self.showPassword_2.setIconSize(QtCore.QSize(25, 25))
        self.showPassword_2.setCheckable(True)
        self.showPassword_2.setObjectName("showPassword_2")
        self.horizontalLayout_2.addWidget(self.showPassword_2)
        self.verticalLayout_7.addWidget(self.frame_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_15.setStyleSheet("background:transparent;\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.embedButton = QtWidgets.QPushButton(parent=self.frame_15)
        self.embedButton.setMinimumSize(QtCore.QSize(150, 50))
        self.embedButton.setMaximumSize(QtCore.QSize(300, 150))
        self.embedButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.embedButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background: #EB5E28;\n"
"font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 30px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 100, 43)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(218, 85, 37);\n"
"}\n"
"")
        self.embedButton.setObjectName("embedButton")
        self.gridLayout_7.addWidget(self.embedButton, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_5.setMinimumSize(QtCore.QSize(300, 100))
        self.label_5.setMaximumSize(QtCore.QSize(500, 500))
        self.label_5.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 50px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #EB5E28;\n"
"background:transparent;\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 100))
        self.label_6.setMaximumSize(QtCore.QSize(250, 100))
        self.label_6.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"background:transparent;\n"
"font-weight: 400;\n"
"font-size: 36px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_8.setMaximumSize(QtCore.QSize(1000, 150))
        self.frame_8.setStyleSheet("background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.extractImageInput = QtWidgets.QLineEdit(parent=self.frame_8)
        self.extractImageInput.setStyleSheet("background:transparent;\n"
"padding:0px 30px;")
        self.extractImageInput.setReadOnly(True)
        self.extractImageInput.setObjectName("extractImageInput")
        self.horizontalLayout_5.addWidget(self.extractImageInput)
        self.uploadImageButton = QtWidgets.QPushButton(parent=self.frame_8)
        self.uploadImageButton.setMinimumSize(QtCore.QSize(60, 50))
        self.uploadImageButton.setSizeIncrement(QtCore.QSize(60, 50))
        self.uploadImageButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(56, 54, 50);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"icon:url(:/img/880eef29f787c838e5be91b50d4f475dd29b0bfc (1).ico);\n"
"}")
        self.uploadImageButton.setText("")
        self.uploadImageButton.setIcon(icon6)
        self.uploadImageButton.setIconSize(QtCore.QSize(60, 25))
        self.uploadImageButton.setObjectName("uploadImageButton")
        self.horizontalLayout_5.addWidget(self.uploadImageButton)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(100, 100))
        self.label_7.setMaximumSize(QtCore.QSize(250, 100))
        self.label_7.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"background:transparent;\n"
"font-weight: 400;\n"
"font-size: 36px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.frame = QtWidgets.QFrame(parent=self.frame_10)
        self.frame.setMinimumSize(QtCore.QSize(300, 50))
        self.frame.setMaximumSize(QtCore.QSize(1000, 150))
        self.frame.setStyleSheet("background: rgba(64, 61, 57, 0.7);\n"
"border-radius: 20px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"color: #FFFFFF;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.extractImagePasswordInput = QtWidgets.QLineEdit(parent=self.frame)
        self.extractImagePasswordInput.setMinimumSize(QtCore.QSize(0, 0))
        self.extractImagePasswordInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.extractImagePasswordInput.setStyleSheet("background:transparent;\n"
"padding:0px 20px;")
        self.extractImagePasswordInput.setFrame(False)
        self.extractImagePasswordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.extractImagePasswordInput.setObjectName("extractImagePasswordInput")
        self.horizontalLayout.addWidget(self.extractImagePasswordInput)
        self.showPassword = QtWidgets.QPushButton(parent=self.frame)
        self.showPassword.setStyleSheet("QPushButton{\n"
"background-color:rgb(56, 54, 50);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"icon:url(:/img/output-onlinepngtools (1).png);\n"
"}\n"
"")
        self.showPassword.setText("")
        self.showPassword.setIcon(icon7)
        self.showPassword.setIconSize(QtCore.QSize(25, 25))
        self.showPassword.setCheckable(True)
        self.showPassword.setObjectName("showPassword")
        self.horizontalLayout.addWidget(self.showPassword)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_11.setStyleSheet("background:transparent;\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.extractButton = QtWidgets.QPushButton(parent=self.frame_11)
        self.extractButton.setMinimumSize(QtCore.QSize(150, 50))
        self.extractButton.setMaximumSize(QtCore.QSize(300, 150))
        self.extractButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background: #EB5E28;\n"
"font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 30px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 100, 43)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(218, 85, 37);\n"
"}\n"
"")
        self.extractButton.setObjectName("extractButton")
        self.gridLayout_5.addWidget(self.extractButton, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_16 = QtWidgets.QFrame(parent=self.page_4)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_39 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_39.setMinimumSize(QtCore.QSize(300, 100))
        self.label_39.setMaximumSize(QtCore.QSize(500, 500))
        self.label_39.setStyleSheet("font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 50px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: #EB5E28;\n"
"background:transparent;\n"
"\n"
"")
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_16)
        self.frame_12.setStyleSheet("background:transparent;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setStyleSheet("width: 71;\n"
"height: 49;\n"
"top: 315px;\n"
"left: 826px;\n"
"font-family: Kdam Thmor Pro;\n"
"font-weight: 400;\n"
"font-size: 32px;\n"
"line-height: 100%;\n"
"letter-spacing: 2px;\n"
"text-align: center;\n"
"color: rgba(235, 94, 40, 1);\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_19.addWidget(self.label_8)
        self.gridLayout_6.addWidget(self.frame_12, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.frame_16)
        self.line_2.setStyleSheet("border: 1px solid rgba(255, 255, 255, 1);\n"
"width: 1071.0041450629933;\n"
"top: 360.84px;\n"
"left: 251px;\n"
"angle: 0.15 deg;\n"
"border-width: 1px;\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 2, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_16)
        self.frame_29.setStyleSheet("background:transparent;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.frame_29)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 700))
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical {\n"
"   background:rgb(0, 0, 0);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(235, 94, 40);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background:rgb(235, 94, 40);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background:transparent;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 1px solid grey;\n"
"      background:transparent;\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_20.addWidget(self.scrollArea_2)
        self.gridLayout_6.addWidget(self.frame_29, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_16, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "LSB"))
        self.label_3.setText(_translate("MainWindow", "SECRET"))
        self.label_12.setText(_translate("MainWindow", "Embed message"))
        self.label_13.setText(_translate("MainWindow", "Your Message"))
        self.label_14.setText(_translate("MainWindow", "upload image"))
        self.label_15.setText(_translate("MainWindow", "Password"))
        self.embedButton.setText(_translate("MainWindow", "Embed"))
        self.embedButton.setShortcut(_translate("MainWindow", "Return"))
        self.label_5.setText(_translate("MainWindow", "Extract message"))
        self.label_6.setText(_translate("MainWindow", "upload image"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.extractButton.setText(_translate("MainWindow", "Extract"))
        self.extractButton.setShortcut(_translate("MainWindow", "Return"))
        self.label_39.setText(_translate("MainWindow", "Extract message"))
        self.label_8.setText(_translate("MainWindow", "Your Messages"))
